let pageLeft = document.createElement("button");
pageLeft.setAttribute("id", "pageLeft");
let pageRight = document.createElement("button");
pageRight.setAttribute("id", "pageRight");
let showCase = document.getElementById("showCase");
pageLeft.innerHTML = "<";
pageRight.innerHTML = ">";
showCase.appendChild(pageLeft);
showCase.appendChild(pageRight);
document.getElementById("gallery").style.display = "none";